### ISSUE TITLE
Why do you use selenium?

### ISSUE THREAD

**Issue by sergiosilvar** [luiseduardobr1/VivaRealWebScraping#1]
Just a doubt. Why is selenium needed? Getting the page through `requests` library isn't bringing the HTML needed to be processed, maybe it's dynamically generated?

**Comment by luiseduardobr1** [comment]
Exatamente. Páginas feitas em Javascript ou que utilizam elementos dinâmicos geralmente são analisadas com um navegador automatizado (no caso estou usando o selenium para isso). Neste caso em específico, creio que na época que estava fazendo o código, percebi que só alterando a URL da página, a ordem dos imóveis em todas as páginas muda, ou seja, a cada solicitação do requests um imóvel que poderia estar na primeira página agora aparecia novamente em uma outra página e com isso acabava perdendo outros imóveis.
